services:
  office-supplies-tracker:
    image: ghcr.io/percivalee/office-supplies-tracker:latest
    container_name: office-supplies-tracker
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
